# Generated by Django 2.1.3 on 2018-11-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permi_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_email', models.EmailField(max_length=255, null=True, unique=True)),
                ('user_pass', models.CharField(default='', max_length=50)),
                ('permission', models.ManyToManyField(to='blog.Permission')),
            ],
        ),
    ]
